version: 2

jobs:
  Tests - ESM:
    docker: [{ image: 'circleci/node:10' }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - ESM
          command: yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  Tests - CJS:
    docker: [{ image: 'circleci/node:10' }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - CJS
          command: yarn run test:cjs:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  Tests - UMD:
    docker: [{ image: 'circleci/node:10' }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - CJS
          command: yarn run test:umd:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  Bundlesize:
    docker: [{ image: 'circleci/node:10' }]
    steps:
      - checkout
      - run: yarn
      - run: yarn run bundlesize

workflows:
  version: 2
  Build and Test:
    jobs:
      - Tests - ESM
      - Tests - CJS
      - Tests - UMD
      - Bundlesize
